config/routes.rb
Rails.application.routes.draw do

  root 'statics#homepage'

  get '/faq',            to: 'statics#faq'
  get '/request-thanks', to: 'statics#request-thanks'

<<<<<<< Updated upstream
<<<<<<< Updated upstream
  get '/scuba/steve', to: 'users#admin'
=======
=======
>>>>>>> Stashed changes
<<<<<<< HEAD
  get 'scuba/steve', to: 'user#admin'
=======
  get '/scuba/steve', to: 'users#admin'
>>>>>>> 5f2aa5c5adf3f3b0a12e0867a200937fcf872663
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

  resources :requests

end

app/models/request.rb
class Request < ActiveRecord::Base

  validates :email, presence: true
  validates :email, format: { with: /\w{1,64}@((?:[-\p{L}\d]+\.)+\p{L}{2,})\s*\z/i,
    message: "Invalid email" }
  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :club_memberships, inclusion: { in: [true, false] }
  validates :live_in_sf, inclusion: { in: [true, false] }
  validates :wifi, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def new  
    @request = Request.new()
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      redirect_to request_thanks_path
    else
      flash.now[:error] = "Please check form and try again"
      render :new
    end
  end

  def edit
  end

  def update
  end
  
  def destroy
  end 
end

private
  def request_params
    params.require(:request).permit(:first_name,
                                    :last_name,
                                    :email,
                                    :club_memberships,
                                    :live_in_sf,
                                    :wifi)
  end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def admin
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    @requests = Request.all
=======
=======
>>>>>>> Stashed changes
<<<<<<< HEAD
    @requests = Request.all.limit(10)
=======
    @requests = Request.all
>>>>>>> 5f2aa5c5adf3f3b0a12e0867a200937fcf872663
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.haml
%nav{class: "top-bar", role: "navigation", data: {topbar: true}}
  %ul{class: "title-area"}
    %li{class: "name"}
      %h1
        = link_to 'Take Me North', root_path

  %section{class: "top-bar-section"}
    <!-- Right Nav Section -->
    %ul{class: 'right'}
      %li
        = link_to 'FAQ', faq_url

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Take Me North" %></title>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>

    <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.0.1";
    analytics.load("FcUB1v9dtg8pKpppPcv3QojJNY7eE2nA");
    analytics.page()
  }}();
  </script>

  </head>

  <body>
    <%= render 'layouts/nav' %>
    <% if flash %>
      <% flash.each do |name, msg| %>
        <%= content_tag(:small, msg, :class => "#{name}") %>
      <% end %>
      <% flash.discard %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/requests/new.html.haml
- @request.errors.messages.each do |field, message|
  %li.small-2.columns= message.first

.row{style: "padding: 4% 0 0 20%"}
=form_for @request, url: {action: "create"} do |f|
  .row
    .small-4.large-3.columns
      %lable First Name
      =f.text_field :first_name, required: true

    .small-4.large-3.columns
      %lable Last Name
      =f.text_field :last_name, required: true
    
    .small-4.large-6.columns

  .row
    .small-8.large-4.columns
      %lable Email
      =f.text_field :email, required: true
  
  .row
    .small-4.large-3.columns
      %lable Do you live in the Bay Area?
      =select(:request, :live_in_sf, options_for_select([['No', false], ['Yes', true]]) )

    .small-6.large-3.columns
      %lable I want a vehicle with Wi-Fi:
      =select(:request, :wifi, options_for_select([['No', false], ['Yes', true]]) )

    .small-2.large-6.columns

  .row
    .small-5.large-4.columns
      %lable Do you have any wine club memberships?
      =select(:request, :club_memberships, options_for_select([['No', false], ['Yes', true]]) )

  .row
    .small-4.columns
      =f.submit "Submit Request"

app/views/statics/faq.html.haml
%h1 FAQ

%ul{class: "accordion", data: {accordion: true}}
  
  %li{class: "accordion-navigation"}
    %a{href: "#panel1a"} How do I book a trip up north?
    %div{id:"panel1a", class: "content active"}
      Visit the
      =link_to('request form', new_request_path)
      and someone will be in touch with you shortly thereafter.

  %li{class: "accordion-navigation"}
    %a{href:"#panel2a"} How much does the trip cost?
    %div{id:"panel2a", class: "content"}
      Visit Napa or Sonoma for a day to experience wines at some of the best wineries in the world at a cost of $700/couple and $200 for each subsequent person. This includes all tastings, lunch, and transportation to/from the SF Bay Area.

  %li{class: "accordion-navigation"}
    %a{href:"#panel3a"} What's included?
    %div{id:"panel3a", class: "content"}
      All tastings, lunch, and transportation to/from the SF Bay Area are included in the cost. Wine, shipments, and any other purchases are NOT included in this cost.

  %li{class: "accordion-navigation"}
    %a{href: "#panel4a"} Can we bring kids along?
    %div{id:"panel4a", class: "content"}
      Kids are more than welcome to join and charged at flat rate $200/person if under 18. Note that not all wineries allow kids and adjustments will need to be made in these cases.

  %li{class: "accordion-navigation"}
    %a{href: "#panel5a"} Is lunch included?
    %div{id:"panel5a", class: "content"}
      Yes. Lunch is included in the cost of the tour.

  %li{class: "accordion-navigation"}
    %a{href: "#panel6a"} Do I need to get to wine country before the tour?
    %div{id:"panel6a", class: "content"}
      Nope. If you're in San Francisco, Oakland, Sonoma, Napa, or anywhere in between then a pick up is included.


  %li{class: "accordion-navigation"}
    %a{href: "#panel7a"} If I decide to purchase wines, can I ship them home?
    %div{id:"panel7a", class: "content"}
      This depends on where you live. If you don't live in California we can discuss your options before you make any purchasing decisions.


  %li{class: "accordion-navigation"}
    %a{href: "#panel8a"} How do we get up there?
    %div{id:"panel8a", class: "content"}
      We'll be driving up in a beautiful Audi. All cars are clean and no older than a year. You can even request WiFi!


  %li{class: "accordion-navigation"}
    %a{href: "#panel9a"} Cars have WiFi!?!
    %div{id:"panel9a", class: "content"}
      If requested, yes. Although this comes at an added cost of $50 for the day. It's still an Audi :)

  %li{class: "accordion-navigation"}
    %a{href: "#panel10a"} I can't make it. What's your cancelation policy?
    %div{id:"panel10a", class: "content"}
      We understand that things come up. Cancellations less than a week out will be assessed a $200 cancellation fee.

app/views/statics/homepage.html.haml
:scss
  body{
    background-image: url('assets/vineyard.jpg');
    background-repeat: no-repeat;
    background-size: cover;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    width: 100% !important;
    z-index: 0;
    }
.row{style: "padding-top: 20%;"}
  .small-3.small-centered.columns{style: "width: 205px;"}
    =link_to "Take Me North!", new_request_url, {class: "button", style: "background-color: #F07154;"}

app/views/statics/request-thanks.html.haml
Thank you for interest in a trip up north. We'll be in touch over the next few days if we are able to accomodate your request.

app/views/users/admin.html.haml
<<<<<<< Updated upstream
<<<<<<< Updated upstream
=======
=======
>>>>>>> Stashed changes
<<<<<<< HEAD
-@request.each do |request|
  = p request

=======
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
%table
  %thead
    %tr
      %th{width:"150"} First Name
      %th{width:"150"} Last Name
      %th{width:"200"} Email

  %tbody
  -@requests.each do |r|
    %tr 
      %td= r.first_name
      %td= r.last_name
      %td= r.email

=@requests.count
<<<<<<< Updated upstream
<<<<<<< Updated upstream
=======
>>>>>>> 5f2aa5c5adf3f3b0a12e0867a200937fcf872663
>>>>>>> Stashed changes
=======
>>>>>>> 5f2aa5c5adf3f3b0a12e0867a200937fcf872663
>>>>>>> Stashed changes